"""add events table v1

Revision ID: 3719c78f3e68
Revises: 956b90d8277b
Create Date: 2021-12-08 16:19:57.970063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3719c78f3e68'
down_revision = '956b90d8277b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_sender_id', table_name='events')
    op.alter_column('gemuese', 'veg_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gemuese', 'veg_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_events_sender_id', 'events', ['sender_id'], unique=False)
    # ### end Alembic commands ###
